image: node
before_script:
  - npm install -g pnpm
  - pnpm install
stages:
  - build
  - deploy
build-code:
  stage: build
  script:
    - echo "build code!"
    - pnpm generate
cache:
  paths:
    - node_modules/
    - .output/
    - dist/
pages:
  stage: deploy
  script:
    - rm -rf public/*
    - mkdir -p public
    - mv dist/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production
